---

- name: Grab The Current Release
  become: true
  shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Fix Permissions
  become:  true
  file: 
    path: /usr/local/bin/docker-compose
    mode: 0764

