"""added id stats timestamp

Revision ID: 07e3f951ca86
Revises: 
Create Date: 2022-03-21 07:54:54.619979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e3f951ca86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ids_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ids_stats_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ids_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ids_stats_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
