"""empty message

Revision ID: 28f41700b9d7
Revises: 8fe473085a28
Create Date: 2022-02-01 10:36:08.251987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f41700b9d7'
down_revision = '8fe473085a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('alert_average', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'alert_average')
    # ### end Alembic commands ###
