"""empty message

Revision ID: 562eeadc49d7
Revises: f195ba3e93f7
Create Date: 2022-01-31 16:58:02.233829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562eeadc49d7'
down_revision = 'f195ba3e93f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stats')
    # ### end Alembic commands ###
