"""empty message

Revision ID: 8fe473085a28
Revises: 562eeadc49d7
Create Date: 2022-01-31 17:08:41.331467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe473085a28'
down_revision = '562eeadc49d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('alert_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'alert_count')
    # ### end Alembic commands ###
