"""empty message

Revision ID: cfdfd36ae9c0
Revises: d86b6e1ad5cb
Create Date: 2022-02-11 11:17:46.834543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdfd36ae9c0'
down_revision = 'd86b6e1ad5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'log_source', ['ids_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log_source', type_='unique')
    # ### end Alembic commands ###
