"""empty message

Revision ID: d86b6e1ad5cb
Revises: 6f4584d0f392
Create Date: 2022-02-02 13:17:03.476099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86b6e1ad5cb'
down_revision = '6f4584d0f392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ids_alert', sa.Column('normalised_severity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ids_alert', 'normalised_severity')
    # ### end Alembic commands ###
