"""empty message

Revision ID: f195ba3e93f7
Revises: 
Create Date: 2022-01-06 13:29:55.560171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f195ba3e93f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ids_name', sa.String(length=128), nullable=True),
    sa.Column('reliability', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('access_token', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('ids_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dest_ip', sa.String(length=120), nullable=True),
    sa.Column('src_ip', sa.String(length=120), nullable=True),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('ids_name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('log_source', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_source'], ['log_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ids_alert_timestamp'), 'ids_alert', ['timestamp'], unique=False)
    op.create_table('target_networkID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_string', sa.String(length=128), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['target_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['ids_alert.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_networkID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_string', sa.String(length=128), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['user_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_networkID')
    op.drop_table('user_alert')
    op.drop_table('user_asset')
    op.drop_table('target_networkID')
    op.drop_index(op.f('ix_ids_alert_timestamp'), table_name='ids_alert')
    op.drop_table('ids_alert')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('target_asset')
    op.drop_table('log_source')
    # ### end Alembic commands ###
