# Config file for the API/UI portion of the Advanced CTF Scoring System.
# Defualt Config Used Only For flask db init
---
flask_options:
    # Use this section to modify the var used by flask and the flask plugins
    SQLALCHEMY_DATABASE_URI: sqlite:////var/lib/ctfscore/Web/app.db
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SECRET_KEY: ddf5986956c8e276a4a56c22bf8d2901b8dac176e968ed132ba4752e37eacaac
api_options:
    # Use this section to modify settings specific to the api itself
    # List of assets and their associated network identifiers, these will be
    # fed into the scoring algorithm and will adjust the score given to each 
    # attack based ont affected asset.
    registered_assets:
    - asset:
        name: placeholder
        value: 0
        network_names:
        - 257.257.0.257
    # List of valid api keys and IDs registered with log aggregator instances.
    # This of course, is not at all secure enough for a normal API deployment.
    # But, this is probably the best way to authenticate API requests 
    # without adding a ton of complexity
    key_pairs:

ui_options:
  # Use this section to modify settings specific to the UI
  monitoring_stack:
    flask_metrics:
      enabled: False
    flask_dashboard:
      enabled: True
  dynamic_ids:
    enabled: False
    expected_ids:
      - Wazuh
      - Suricata