
# Wazuh - Filebeat configuration file
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.template.overwrite: true
setup.ilm.enabled: false
output.elasticsearch:
  hosts: ['https://elasticsearch:9200']
  username: 'admin'
  password: 'admin'
  ssl.verification_mode: none
  #ssl.certificate_authorities:
  #ssl.certificate:
  #ssl.key:
