---
# Advanced CTF Scoring System - Example Cofing.
# ALl keys in this section are mandatory
global_options:
    # The base url of the API that will receive the IDS alerts
    api_url: https://192.168.56.107/api 
    # How long to wait (in ms) between reading and forwarding alerts to the api
    polling_rate: 250
    # Paths for the API Key and ID files. These must match the values set in
    # the api. Documentation of setting these values on the API side is 
    # available here: 
    api_key_file: Source/Logging/test_key.txt
    api_id_file: Source/Logging/test_id.txt
    ssl_cert_file: /etc/ctfscore/cert
    # These are added to the base url
    api_status_endpoint: "/status"
    api_forward_event_endpoint: "/forward"
    # The maximium number of **consecutive** failures since the last succesful
    # interaction with the api.
    api_max_retries: 5
    # It can be useful to disable the API when developing the log aggregator
    api_is_enabled: true
# This section is mandatory howerver, there are no set limits on the number of 
#IDS provided, that there is at least one **vaid** IDS
ids_options:
  - ids: 
      log_file_format:
      # This section is used to define the JSON keys that IDS uses to represent
      # different values. Example documentaion on this can be found here. Note 
      # that the system uses JSON pointer syntax
        fields:
          timestamp: /time_local
          src_ip: /remote_addr
          dest_ip: /request_uri
          message: /category
        # Path to the file that contains the IDS alerts
        path: Test/Files/teler.json
      # The maximum number of **valid** alerts to read and forward to the api
      # everytime the log is read. Useful, for controlling load on the network
      # and system
      max_alerts: 20
      name: "teler"
      # Percentage used to represent the false postive rate of the IDS and thus, weight
      # the scoring alogritim
      reliability: 75
  - ids: 
      log_file_format:
        fields:
          timestamp: /timestamp
          src_ip: /src_ip
          dest_ip: /dest_ip
          message: /alert/signature
          severity: /alert/severity
        path: Test/Files/bigeve.json
      max_alerts: 20
      name: "Suricata"
      reliability: 50
